# Generated by Django 5.2.9 on 2025-12-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('contact_email', models.EmailField(max_length=254)),
                ('plan_name', models.CharField(max_length=20)),
                ('status', models.CharField(default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
