# Generated by Django 5.2.9 on 2025-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('company', 'rut')},
        ),
    ]
