# Generated by Django 5.2.9 on 2025-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku_alter_supplier_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ALIMENTOS', 'Alimentos y Comestibles'), ('BEBIDAS', 'Bebidas y Licores'), ('SNACKS', 'Snacks y Confitería'), ('LIMPIEZA', 'Productos de Limpieza'), ('HIGIENE', 'Higiene Personal'), ('FARMACIA', 'Medicamentos / Farmacia'), ('TECNOLOGIA', 'Electrónica y Tecnología'), ('HOGAR', 'Artículos para el Hogar'), ('JUGUETES', 'Juguetes'), ('ROPA', 'Vestimenta y Accesorios'), ('DEPORTES', 'Deportes'), ('JARDIN', 'Jardinería'), ('MASCOTAS', 'Productos para Mascotas'), ('LIBROS', 'Libros y Papelería'), ('VEHICULOS', 'Accesorios para Vehículos'), ('HERRAMIENTAS', 'Herramientas'), ('SERVICIOS', 'Servicios'), ('CONGELADOS', 'Congelados'), ('FRESCOS', 'Productos Frescos'), ('OTROS', 'Otros / Varios')], max_length=50),
        ),
    ]
